version: "3"

services:
  phpfpm:
    image: itkdev/php7.4-fpm
    environment:
      - XDEBUG_MODE=${XDEBUG_MODE:-off}
      - XDEBUG_SESSION=${XDEBUG_SESSION:-0}
      - PHP_MAX_EXECUTION_TIME=30
      - PHP_MEMORY_LIMIT=256M
      - DOCKER_HOST_DOMAIN=${COMPOSE_DOMAIN}
      - PHP_IDE_CONFIG=serverName=localhost
      - COMPOSER_VERSION=2
    volumes:
      - .:/app:delegated
    tmpfs:
      - /app/var/cache:size=1G
      - /tmp:size=1G
